apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: jwenz723/podlifecycle
      context: ./
      docker:
        dockerfile: ./Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - ./k8s/*
portForward:
  - resourceType: service
    resourceName: podlifecycle
    port: 8080
    localPort: 8080
