apiVersion: v1
kind: Service
metadata:
  name: podlifecycle
  labels:
    app: podlifecycle
spec:
  ports:
    - port: 8080
      name: grpc-server
  selector:
    app: podlifecycle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podlifecycle
  name: podlifecycle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podlifecycle
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: podlifecycle
    spec:
      containers:
        - args:
            - while true; do echo sleeping...; sleep 30; done;
          command:
            - ash
            - -c
            - --
          image: jwenz723/grpchealthprobe
          livenessProbe:
            exec:
              command:
                - /usr/bin/local/grpc-health-probe
                - -addr=:8080
            initialDelaySeconds: 10
          name: grpchealthprobe
          readinessProbe:
            exec:
              command:
                - /usr/bin/local/grpc-health-probe
                - -addr=:8080
            initialDelaySeconds: 5
        - image: jwenz723/podlifecycle
          name: podlifecycle
          ports:
            - containerPort: 8080
      terminationGracePeriodSeconds: 50
